name: "dbt_ny_taxi_analytics"
version: "1.0.0"
config-version: 2

profile: "dbt_ny_taxi_analytics"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  dbt_ny_taxi_analytics: {}
